-- Migration: Create prebooking foundation
-- Generated by Antigravity on 2026-07-17

-- 1. Enum for calendar slot status
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'calendar_slot_status' AND typnamespace = 'public'::regnamespace) THEN
        CREATE TYPE public.calendar_slot_status AS ENUM (
            'open',
            'reserved',
            'blocked'
        );
    END IF;
END $$;

-- 2. Table: calendar_slots
CREATE TABLE IF NOT EXISTS public.calendar_slots (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    slot_date date NOT NULL,
    start_time time WITHOUT TIME ZONE NOT NULL,
    end_time time WITHOUT TIME ZONE NOT NULL,
    status public.calendar_slot_status NOT NULL DEFAULT 'open',
    professional_name text,
    notes text,
    published boolean NOT NULL DEFAULT true,
    reserved_at timestamptz,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chk_end_after_start CHECK (end_time > start_time),
    CONSTRAINT chk_prof_name_len CHECK (char_length(coalesce(professional_name, '')) <= 200),
    CONSTRAINT chk_notes_len CHECK (char_length(coalesce(notes, '')) <= 2000)
);

-- Trigger to keep updated_at in sync
DROP TRIGGER IF EXISTS calendar_slots_updated ON public.calendar_slots;
CREATE TRIGGER calendar_slots_updated
    BEFORE UPDATE ON public.calendar_slots
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- Unique active slot (prevent duplicate active slots)
CREATE UNIQUE INDEX IF NOT EXISTS calendar_slots_unique_active ON public.calendar_slots (
    slot_date,
    start_time,
    end_time,
    COALESCE(professional_name, '')
) WHERE deleted_at IS NULL;

-- 3. Table: slot_templates
CREATE TABLE IF NOT EXISTS public.slot_templates (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    weekdays smallint[] NOT NULL,
    available_times jsonb NOT NULL,
    valid_from date,
    valid_until date,
    favorite boolean NOT NULL DEFAULT false,
    active boolean NOT NULL DEFAULT true,
    professional_name text,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chk_name_not_empty CHECK (btrim(name) <> ''),
    CONSTRAINT chk_name_len CHECK (char_length(name) <= 200),
    CONSTRAINT chk_weekdays_not_empty CHECK (array_length(weekdays, 1) IS NOT NULL AND array_length(weekdays, 1) > 0),
    CONSTRAINT chk_weekday_range CHECK (
      array_position(weekdays, NULL) IS NULL 
      AND weekdays <@ ARRAY[0,1,2,3,4,5,6]::smallint[]
    ),
    CONSTRAINT chk_available_times_array CHECK (jsonb_typeof(available_times) = 'array' AND jsonb_array_length(available_times) > 0),
    CONSTRAINT chk_valid_dates CHECK (valid_from IS NULL OR valid_until IS NULL OR valid_until >= valid_from),
    CONSTRAINT chk_prof_name_len_template CHECK (char_length(coalesce(professional_name, '')) <= 200)
);

DROP TRIGGER IF EXISTS slot_templates_updated ON public.slot_templates;
CREATE TRIGGER slot_templates_updated
    BEFORE UPDATE ON public.slot_templates
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- 4. Table: slot_exceptions
CREATE TABLE IF NOT EXISTS public.slot_exceptions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    start_time time WITHOUT TIME ZONE,
    end_time time WITHOUT TIME ZONE,
    reason text,
    professional_name text,
    created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    CONSTRAINT chk_name_not_empty_exc CHECK (btrim(name) <> ''),
    CONSTRAINT chk_name_len_exc CHECK (char_length(name) <= 200),
    CONSTRAINT chk_dates CHECK (end_date >= start_date),
    CONSTRAINT chk_time_pair CHECK ((start_time IS NULL AND end_time IS NULL) OR (start_time IS NOT NULL AND end_time IS NOT NULL)),
    CONSTRAINT chk_end_after_start_exc CHECK (start_time IS NULL OR end_time IS NULL OR end_time > start_time),
    CONSTRAINT chk_reason_len CHECK (char_length(coalesce(reason, '')) <= 2000),
    CONSTRAINT chk_prof_name_len_exc CHECK (char_length(coalesce(professional_name, '')) <= 200)
);

DROP TRIGGER IF EXISTS slot_exceptions_updated ON public.slot_exceptions;
CREATE TRIGGER slot_exceptions_updated
    BEFORE UPDATE ON public.slot_exceptions
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- 5. Extend appointments table
ALTER TABLE public.appointments
    ADD COLUMN IF NOT EXISTS calendar_slot_id uuid,
    ADD COLUMN IF NOT EXISTS submitted_at timestamptz,
    ADD COLUMN IF NOT EXISTS confirmed_at timestamptz,
    ADD COLUMN IF NOT EXISTS cancelled_at timestamptz,
    ADD COLUMN IF NOT EXISTS handled_by uuid;

-- Foreign keys
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM pg_constraint 
        WHERE conname = 'fk_appointments_calendar_slot' 
          AND conrelid = 'public.appointments'::regclass
    ) THEN
        ALTER TABLE public.appointments
            ADD CONSTRAINT fk_appointments_calendar_slot 
            FOREIGN KEY (calendar_slot_id) 
            REFERENCES public.calendar_slots(id) 
            ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM pg_constraint 
        WHERE conname = 'fk_appointments_handled_by' 
          AND conrelid = 'public.appointments'::regclass
    ) THEN
        ALTER TABLE public.appointments
            ADD CONSTRAINT fk_appointments_handled_by 
            FOREIGN KEY (handled_by) 
            REFERENCES auth.users(id) 
            ON DELETE SET NULL;
    END IF;
END $$;

-- Index for fast lookup of appointments by slot
CREATE INDEX IF NOT EXISTS idx_appointments_calendar_slot_id ON public.appointments (calendar_slot_id);

-- Unique reservation per slot (prevent double booking of open slots)
CREATE UNIQUE INDEX IF NOT EXISTS uq_appointments_active_slot ON public.appointments (calendar_slot_id)
    WHERE calendar_slot_id IS NOT NULL AND status IN ('pending', 'confirmed', 'completed');

-- 6. Enable RLS on new tables
ALTER TABLE public.calendar_slots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.slot_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.slot_exceptions ENABLE ROW LEVEL SECURITY;

-- Grants for new tables
GRANT SELECT ON public.calendar_slots TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calendar_slots TO authenticated;
GRANT ALL ON public.calendar_slots TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.slot_templates TO authenticated;
GRANT ALL ON public.slot_templates TO service_role;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.slot_exceptions TO authenticated;
GRANT ALL ON public.slot_exceptions TO service_role;

-- 7. Policies for calendar_slots (public)
DROP POLICY IF EXISTS calendar_slots_public_select ON public.calendar_slots;
CREATE POLICY calendar_slots_public_select ON public.calendar_slots
    FOR SELECT TO anon, authenticated
    USING (
        published = true
        AND status = 'open'
        AND deleted_at IS NULL
        AND (
            slot_date > (now() AT TIME ZONE 'America/Sao_Paulo')::date
            OR (slot_date = (now() AT TIME ZONE 'America/Sao_Paulo')::date
                AND start_time > (now() AT TIME ZONE 'America/Sao_Paulo')::time)
        )
    );

-- Admin policies (all actions) for calendar_slots
DROP POLICY IF EXISTS calendar_slots_admin ON public.calendar_slots;
CREATE POLICY calendar_slots_admin ON public.calendar_slots
    FOR ALL TO authenticated
    USING (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

-- Admin policies for slot_templates
DROP POLICY IF EXISTS slot_templates_admin ON public.slot_templates;
CREATE POLICY slot_templates_admin ON public.slot_templates
    FOR ALL TO authenticated
    USING (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

-- Admin policies for slot_exceptions
DROP POLICY IF EXISTS slot_exceptions_admin ON public.slot_exceptions;
CREATE POLICY slot_exceptions_admin ON public.slot_exceptions
    FOR ALL TO authenticated
    USING (public.is_admin(auth.uid()))
    WITH CHECK (public.is_admin(auth.uid()));

-- 8. Revoke direct INSERT on appointments for public users
DROP POLICY IF EXISTS "Anyone can create appointments" ON public.appointments;
REVOKE INSERT ON public.appointments FROM anon, authenticated;

-- 9. RPC: create_prebooking
DROP FUNCTION IF EXISTS public.create_prebooking(uuid, text, text, text, uuid, text);
CREATE OR REPLACE FUNCTION public.create_prebooking(
    p_calendar_slot_id uuid,
    p_full_name text,
    p_phone text,
    p_email text,
    p_service_id uuid,
    p_notes text
) RETURNS TABLE (
    appointment_id uuid,
    slot_id uuid,
    appointment_status text,
    submitted_at timestamptz
) LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp AS
$$
DECLARE
    v_user_id uuid := auth.uid();
    v_service public.services%ROWTYPE;
    v_slot public.calendar_slots%ROWTYPE;
    v_appointment_id uuid;
BEGIN
    -- Validate full_name
    IF p_full_name IS NULL OR btrim(p_full_name) = '' THEN RAISE EXCEPTION 'Nome inválido.'; END IF;
    IF char_length(btrim(p_full_name)) > 200 THEN RAISE EXCEPTION 'Nome inválido.'; END IF;

    -- Validate phone
    IF p_phone IS NULL OR btrim(p_phone) = '' THEN RAISE EXCEPTION 'Telefone inválido.'; END IF;
    IF char_length(btrim(p_phone)) > 40 THEN RAISE EXCEPTION 'Telefone inválido.'; END IF;

    -- Normalize optional fields
    p_email := nullif(btrim(p_email), '');
    IF p_email IS NOT NULL THEN
        IF char_length(p_email) > 320 THEN
            RAISE EXCEPTION 'E-mail inválido.';
        END IF;
        IF NOT p_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' THEN
            RAISE EXCEPTION 'E-mail inválido.';
        END IF;
    END IF;

    p_notes := nullif(btrim(p_notes), '');
    IF p_notes IS NOT NULL AND char_length(p_notes) > 2000 THEN
        RAISE EXCEPTION 'Observações inválidas.';
    END IF;

    -- Database transaction block to handle serialization/deadlock/unique violations
    BEGIN
        -- Verify service
        SELECT * INTO v_service FROM public.services WHERE id = p_service_id AND active = true;
        IF NOT FOUND THEN RAISE EXCEPTION 'Serviço indisponível.'; END IF;

        -- Verify slot availability (locks the row for update)
        SELECT * INTO v_slot FROM public.calendar_slots
            WHERE id = p_calendar_slot_id
              AND deleted_at IS NULL
              AND published = true
              AND status = 'open'
              AND (
                    slot_date > (now() AT TIME ZONE 'America/Sao_Paulo')::date
                    OR (slot_date = (now() AT TIME ZONE 'America/Sao_Paulo')::date
                        AND start_time > (now() AT TIME ZONE 'America/Sao_Paulo')::time)
                  )
            FOR UPDATE;
        IF NOT FOUND THEN RAISE EXCEPTION 'Horário indisponível.'; END IF;

        -- Create appointment
        INSERT INTO public.appointments (
            calendar_slot_id,
            user_id,
            full_name,
            phone,
            email,
            service,
            preferred_date,
            preferred_time,
            notes,
            status,
            source,
            submitted_at,
            handled_by
        ) VALUES (
            p_calendar_slot_id,
            v_user_id,
            btrim(p_full_name),
            btrim(p_phone),
            p_email,
            v_service.name,
            v_slot.slot_date,
            to_char(v_slot.start_time,'HH24:MI'),
            p_notes,
            'pending',
            'website_prebooking',
            now(),
            NULL
        ) RETURNING id INTO v_appointment_id;

        -- Reserve the slot
        UPDATE public.calendar_slots SET status = 'reserved', reserved_at = now()
        WHERE id = p_calendar_slot_id AND status = 'open' AND deleted_at IS NULL;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Horário indisponível.';
        END IF;

        RETURN QUERY SELECT v_appointment_id, p_calendar_slot_id, 'pending'::text, now();
    EXCEPTION
        WHEN unique_violation OR serialization_failure OR deadlock_detected THEN
            RAISE EXCEPTION 'Horário indisponível.';
    END;
END;
$$;

-- Grant execute on the RPC (specific signature)
REVOKE ALL ON FUNCTION public.create_prebooking(uuid, text, text, text, uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_prebooking(uuid, text, text, text, uuid, text) TO anon, authenticated, service_role;

-- 10. Additional indexes for new tables (optional but useful)
CREATE INDEX IF NOT EXISTS idx_calendar_slots_date_status ON public.calendar_slots (slot_date, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_slot_templates_active ON public.slot_templates (active) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_slot_exceptions_dates ON public.slot_exceptions (start_date, end_date) WHERE deleted_at IS NULL;

-- Migration completed.
